version: '3.1'

services:

  wordpress:
    image: wordpress:6.3.2-fpm
    restart: always
    container_name: wordpress-fpm
    # ports:
    #   - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    container_name: wordpress-mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: wordpress-nginx
    ports:
      - 80:80    
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

volumes:
  wordpress:
  db:
